language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_install:
  - node --version
  - npm --version

matrix:
  allow_failures:
    - node_js: "0.11"
    - node_js: "0.8"
    - node_js: "0.6"

notifications:
  email:
    - simon@simondean.org
